title: Neil's Blog
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
enable_copy_code_button: true

url: https://just-the-docs.github.io

aux_links:
  Personal Page: https://www.neilhommes.xyz
