title: Neil's Blog
description: A simple blog for ctf writeups and tutorials.
theme: just-the-docs
enable_copy_code_button: true
color_scheme: dark
gems:
  - jekyll-seo-tag

url: https://just-the-docs.github.io

aux_links:
  Personal Page: https://www.neilhommes.xyz

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  remember:
    title: Remember
    color: green
