version: "3.7"
services:
    blog:
        container_name: blog
        restart: always
        build:
            dockerfile: Dockerfile
            context: .
        logging:
            driver: "json-file"
        ports:
            - "2345:4000"